Version:
  AppVer: 7
  MinAppVer: 7
  Show: v0.6.0
downloadpathminlen: 88
Port: "9081"
NetworkAddress: 127.0.0.1
Debug: true
PPListDir: ./peers
AccountDir: ./accounts
StorehousePath: ./storage
DownloadPath: ./download
P2PAddress: stsds1gl9ywg6jdfdgcja70ffum4ectq4fmt26ay4znv
P2PPassword: aaa
WalletAddress: st1jn9skjsnxv26mekd8eu8a8aquh34v0m4mwgahg
WalletPassword: aaa
AutoRun: true
Internal: false
IsWallet: true
IsLimitDownloadSpeed: false
LimitDownloadSpeed: 100
IsLimitUploadSpeed: false
LimitUploadSpeed: 100
ChainId: test-chain
Token: ustos
StratosChainUrl: http://127.0.0.1:1317
StreamingCache: false
RestPort: "18091"
InternalPort: "9608"
TrafficLogInterval: 10
SPList:
- P2PAddress:
  P2PPublicKey:
  NetworkAddress: 0.0.0.0:8888

