Version:
  AppVer: 7
  MinAppVer: 7
  Show: v0.6.0
downloadpathminlen: 88
Port: "9084"
NetworkAddress: 127.0.0.1
Debug: true
PPListDir: ./peers
AccountDir: ./accounts
StorehousePath: ./storage
DownloadPath: ./download
P2PAddress: stsds1ttpyyh9p7udalhwcz7sh5f5zfzuhpm0h3c0hzc
P2PPassword: aaa
WalletAddress: st1pztt40kk7mr3jsfcpymz43fz44fc0nc5wtkeq7
WalletPassword: aaa
AutoRun: true
Internal: false
IsWallet: true
IsLimitDownloadSpeed: false
LimitDownloadSpeed: 100
IsLimitUploadSpeed: false
LimitUploadSpeed: 100
ChainId: test-chain
Token: ustos
StratosChainUrl: http://127.0.0.1:1317
StreamingCache: false
RestPort: "18094"
InternalPort: ""
TrafficLogInterval: 10
SPList:
- P2PAddress:
  P2PPublicKey:
  NetworkAddress: 0.0.0.0:8888

