Version:
  AppVer: 7
  MinAppVer: 7
  Show: v0.6.0
downloadpathminlen: 88
Port: "9083"
NetworkAddress: 127.0.0.1
Debug: true
PPListDir: ./peers
AccountDir: ./accounts
StorehousePath: ./storage
DownloadPath: ./download
P2PAddress: stsds1xg2jzku8gptq6sjpjd9zus8qec7a39phcj8md9
P2PPassword: aaa
WalletAddress: st142ndkgqu2earnvp28ur09dg62sd39xqwyux46a
WalletPassword: aaa
AutoRun: true
Internal: false
IsWallet: true
IsLimitDownloadSpeed: false
LimitDownloadSpeed: 100
IsLimitUploadSpeed: false
LimitUploadSpeed: 100
ChainId: test-chain
Token: ustos
StratosChainUrl: http://127.0.0.1:1317
StreamingCache: false
RestPort: "18093"
InternalPort: ""
TrafficLogInterval: 10
SPList:
- P2PAddress:
  P2PPublicKey:
  NetworkAddress: 0.0.0.0:8888

