Version:
  AppVer: 7
  MinAppVer: 7
  Show: v0.6.0
downloadpathminlen: 88
Port: "9082"
NetworkAddress: 127.0.0.1
Debug: true
PPListDir: ./peers
AccountDir: ./accounts
StorehousePath: ./storage
DownloadPath: ./download
P2PAddress: stsds1faej5w4q6hgnt0ft598dlm408g4p747y4krwca
P2PPassword: aaa
WalletAddress: st1ppcc7hmgwnr6e67ad4tcxxyskqpahuc2y4w7yq
WalletPassword: aaa
AutoRun: true
Internal: false
IsWallet: true
IsLimitDownloadSpeed: false
LimitDownloadSpeed: 100
IsLimitUploadSpeed: false
LimitUploadSpeed: 100
ChainId: test-chain
Token: ustos
StratosChainUrl: http://127.0.0.1:1317
StreamingCache: false
RestPort: "18092"
InternalPort: ""
TrafficLogInterval: 10
SPList:
- P2PAddress: 
  P2PPublicKey: 
  NetworkAddress: 0.0.0.0:8888

